env:
  es6: true
  node: true

extends: 'airbnb-base'

globals:
  assert: true
  browser: true

parserOptions:
  ecmaVersion: 2017

root: true

rules:
  comma-dangle:
    - 'error'
    - arrays: 'always-multiline'
      objects: 'always-multiline'
      imports: 'never'
      exports: 'never'
      functions: 'ignore'
  global-require: 'off'
  import/no-extraneous-dependencies: 0
  indent:
    - 'error'
    - 2
    - SwitchCase: 1
  max-len:
    - 'error'
    - 120
    - ignorePattern: '\s*\/\^(.*)\$\/,$'
  new-cap:
    - 'error'
    - newIsCap: true
  require-jsdoc:
    - 'off'
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  strict: 'off'
  valid-jsdoc:
    - 'warn'
    - requireReturn: false
      matchDescription: '.+'
  no-await-in-loop: 'off'
  linebreak-style: off
  func-names: off
